export const cards = [
  {
    id: 1,
    topic: "Web Design",
    title: "Верстка главной страницы",
    date: "12.01.2026",
    status: "Без статуса",
  },
  {
    id: 2,
    topic: "Research",
    title: "Анализ конкурентов",
    date: "13.01.2026",
    status: "В работе",
  },
  {
    id: 3,
    topic: "Copywriting",
    title: "Тексты для лендинга",
    date: "14.01.2026",
    status: "Готово",
  },
  {
    id: 4,
    topic: "Web Design",
    title: "Создание макета мобильной версии",
    date: "15.01.2026",
    status: "Нужно сделать",
  },
  {
    id: 5,
    topic: "Research",
    title: "Сбор требований пользователя",
    date: "16.01.2026",
    status: "Тестирование",
  },
  {
    id: 6,
    topic: "Copywriting",
    title: "Подготовка описаний карточек",
    date: "17.01.2026",
    status: "В работе",
  },
  {
    id: 7,
    topic: "Web Design",
    title: "Адаптивная верстка под планшеты",
    date: "18.01.2026",
    status: "Нужно сделать",
  },
  {
    id: 8,
    topic: "Research",
    title: "Исследование целевой аудитории",
    date: "19.01.2026",
    status: "Готово",
  },
  {
    id: 9,
    topic: "Copywriting",
    title: "Тексты для формы регистрации",
    date: "20.01.2026",
    status: "Без статуса",
  },
  {
    id: 10,
    topic: "Web Design",
    title: "Проработка цветовой схемы",
    date: "21.01.2026",
    status: "В работе",
  },
];
