export const cards = [
  {
    id: 1,
    topic: "Web Design",
    title: "Верстка главной страницы",
    date: "12.01.2026",
    status: "Без статуса",
  },
  {
    id: 2,
    topic: "Frontend",
    title: "React hooks",
    date: "13.01.2026",
    status: "В работе",
  },
  {
    id: 3,
    topic: "Backend",
    title: "Интеграция API",
    date: "14.01.2026",
    status: "Готово",
  },
  {
    id: 4,
    topic: "Design",
    title: "Создание макета мобильной версии",
    date: "15.01.2026",
    status: "Нужно сделать",
  },
  {
    id: 5,
    topic: "Testing",
    title: "Юнит-тесты для компонентов",
    date: "16.01.2026",
    status: "Тестирование",
  },
  {
    id: 6,
    topic: "Backend",
    title: "Настройка базы данных",
    date: "17.01.2026",
    status: "В работе",
  },
  {
    id: 7,
    topic: "Frontend",
    title: "Подключение API к карточкам",
    date: "18.01.2026",
    status: "Нужно сделать",
  },
  {
    id: 8,
    topic: "Web Design",
    title: "Адаптивная верстка под планшеты",
    date: "19.01.2026",
    status: "Готово",
  },
  {
    id: 9,
    topic: "Testing",
    title: "E2E тестирование формы регистрации",
    date: "20.01.2026",
    status: "Без статуса",
  },
  {
    id: 10,
    topic: "Design",
    title: "Проработка цветовой схемы",
    date: "21.01.2026",
    status: "В работе",
  },
];
